// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_Y0wsTTbdH",
    "aws_user_pools_web_client_id": "65hpjp03f0e0e458h4ofmajnjm",
    "oauth": {}
};


export default awsmobile;
